export function JsonLd({ data }: { data: Record<string, unknown> }) {
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} />;
}

export const ORGANIZATION_JSON_LD = { "@context": "https://schema.org", "@type": "Organization", name: "AgriMinds Ecosystem Foundation", url: "https://agriminds.in", logo: "https://agriminds.in/brand/agriminds-icon.png", description: "Nurturing Indian agriculture's next generation of entrepreneurs through a connected ecosystem of farmers, FPOs, founders, mentors, and institutions.", sameAs: [SOCIAL_URLS.linkedin, SOCIAL_URLS.instagram, SOCIAL_URLS.x] };
export const WEBSITE_JSON_LD = { "@context": "https://schema.org", "@type": "WebSite", name: "AgriMinds", alternateName: "AgriMinds Ecosystem Foundation", url: "https://agriminds.in" };
export function breadcrumbJsonLd(items: Array<{ name: string; url: string }>) { return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: item.url })) }; }
export function articleJsonLd({ headline, description, image, datePublished, url }: { headline: string; description: string; image: string; datePublished: string; url: string }) { return { "@context": "https://schema.org", "@type": "Article", headline, description, image: [image], datePublished, author: { "@type": "Organization", name: "AgriMinds Ecosystem Foundation", url: "https://agriminds.in" }, publisher: { "@type": "Organization", name: "AgriMinds Ecosystem Foundation", logo: { "@type": "ImageObject", url: "https://agriminds.in/brand/agriminds-icon.png" } }, mainEntityOfPage: { "@type": "WebPage", "@id": url } }; }
export function videoJsonLd({ name, description, videoId }: { name: string; description: string; videoId: string }) { return { "@context": "https://schema.org", "@type": "VideoObject", name, description, thumbnailUrl: [`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`], embedUrl: `https://www.youtube.com/embed/${videoId}`, contentUrl: `https://www.youtube.com/watch?v=${videoId}` }; }
import { SOCIAL_URLS } from "@/shared/data/links";
