export function JsonLd({ data }: { data: Record<string, unknown> }) {
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} />;
}

export const ORGANIZATION_JSON_LD = { "@context": "https://schema.org", "@type": "Organization", name: "AgriMinds Ecosystem Foundation", url: "https://agriminds.org", logo: "https://agriminds.org/brand/agriminds-icon.png", description: "Nurturing Indian agriculture's next generation of entrepreneurs through a connected ecosystem of farmers, FPOs, founders, mentors, and institutions.", sameAs: [SOCIAL_URLS.linkedin, SOCIAL_URLS.instagram, SOCIAL_URLS.x] };
export const WEBSITE_JSON_LD = { "@context": "https://schema.org", "@type": "WebSite", name: "AgriMinds", alternateName: "AgriMinds Ecosystem Foundation", url: "https://agriminds.org" };
export function breadcrumbJsonLd(items: Array<{ name: string; url: string }>) { return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: item.url })) }; }
export function articleJsonLd({ headline, description, image, datePublished, url }: { headline: string; description: string; image: string; datePublished: string; url: string }) { return { "@context": "https://schema.org", "@type": "Article", headline, description, image: [image], datePublished, author: { "@type": "Organization", name: "AgriMinds Ecosystem Foundation", url: "https://agriminds.org" }, publisher: { "@type": "Organization", name: "AgriMinds Ecosystem Foundation", logo: { "@type": "ImageObject", url: "https://agriminds.org/brand/agriminds-icon.png" } }, mainEntityOfPage: { "@type": "WebPage", "@id": url } }; }
export function videoJsonLd({ name, description, videoId, uploadDate }: { name: string; description: string; videoId: string; uploadDate: string }) { return { "@context": "https://schema.org", "@type": "VideoObject", name, description, uploadDate, thumbnailUrl: [`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`], embedUrl: `https://www.youtube.com/embed/${videoId}`, contentUrl: `https://www.youtube.com/watch?v=${videoId}` }; }
export function eventJsonLd({ name, description, startDate, endDate, location, address, url, image, eventStatus = "https://schema.org/EventCompleted" }: { name: string; description: string; startDate: string; endDate: string; location: string; address: string; url: string; image?: string; eventStatus?: string }) { return { "@context": "https://schema.org", "@type": "Event", name, description, startDate, endDate, eventStatus, eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode", location: { "@type": "Place", name: location, address: { "@type": "PostalAddress", streetAddress: address, addressLocality: "Visakhapatnam", addressRegion: "Andhra Pradesh", addressCountry: "IN" } }, ...(image ? { image: [image] } : {}), organizer: { "@type": "Organization", name: "AgriMinds Ecosystem Foundation", url: "https://agriminds.org" }, url }; }
import { SOCIAL_URLS } from "@/shared/data/links";
