import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Lightbulb, Sprout } from "lucide-react";
import Breadcrumbs from "@/shared/components/seo/breadcrumbs";

export const metadata: Metadata = {
  title: "AgriMinds Hackathon 2026 — Problem Statements",
  description: "Explore the AgriMinds AgriTech Hackathon 2026 problem statements for students and start-ups solving real agricultural value-chain challenges.",
  alternates: { canonical: "/Agritech-summit-2026/hackathon" },
  openGraph: { title: "AgriMinds Hackathon 2026 — Problem Statements", description: "Build practical solutions for real agricultural value-chain challenges at the AgriMinds Hackathon 2026.", url: "https://agriminds.org/Agritech-summit-2026/hackathon" },
};

const problemTracks = [
  ["Pre-Production", ["Seed quality check before sowing", "Soil data that farmers can act on"]],
  ["Production", ["Right-time pest and disease action", "Technology-enabled weed management", "Labour at peak farm operations", "Early warning in small dairy and poultry units"]],
  ["Post-Harvest", ["Independent grading at the point of sale", "Tracking losses in the first leg of the chain", "Consistent quality in micro food processing"]],
  ["Marketing", ["Compliant labels for small food brands", "Viable direct delivery to city buyers"]],
] as const;

const problemBriefs: Record<string, { context: string; realProblem: string; illustration: string }> = {
  "Seed quality check before sowing": { context: "Farmers often save seed from a previous harvest or buy local seed without a quick, trusted way to check whether it will germinate well.", realProblem: "A poor germination rate is discovered only after sowing. Re-sowing costs seed, labour, water, and time, while a laboratory test may be too expensive, slow, or far away.", illustration: "A farmer buys local seed, sows the whole field, and later sees that only half the plants emerge. What could help the farmer test a small sample before risking the entire field?" },
  "Soil data that farmers can act on": { context: "Soil test reports contain useful measurements, but farmers may receive numbers without a simple explanation of what to change in the next crop cycle.", realProblem: "The gap is converting soil data into an affordable, crop-specific decision about fertiliser, sowing, irrigation, or soil improvement.", illustration: "A farmer receives a soil report but still follows last season's fertiliser routine because the report does not explain the next action. How would you turn the report into a decision?" },
  "Right-time pest and disease action": { context: "Pest and disease pressure changes with crop stage, weather, field conditions, and local spread. Farmers often act after visible damage appears.", realProblem: "Farmers need trustworthy advice on whether to act, when to act, what method to use, and the right dose—without unnecessary spraying or delayed intervention.", illustration: "A farmer notices a few damaged leaves and waits. Within a week the pest spreads, or the farmer sprays too early and spends unnecessarily. How could the farmer know when action is justified?" },
  "Technology-enabled weed management": { context: "Weeds emerge unevenly, compete with crops from an early stage, and can be difficult to distinguish from the crop without careful observation.", realProblem: "Farmers need an affordable way to detect weeds early and choose manual, mechanical, biological, or chemical control without increasing crop damage or environmental harm.", illustration: "A farmer sees weeds in only a few parts of the field. By the time the plot is overgrown, manual weeding is expensive and blanket herbicide could damage the crop. How could a phone, sensor, drone, or affordable machine help?" },
  "Labour at peak farm operations": { context: "Weeding, transplanting, and harvesting are time-sensitive operations. Many farms need extra workers during the same short periods.", realProblem: "Workers are difficult to find at the right time, and informal arrangements provide limited visibility into availability, skills, location, and fair rates.", illustration: "A farmer's crop is ready for harvesting, but the usual workers are committed elsewhere. How could the farmer find reliable help or an affordable alternative in time?" },
  "Early warning in small dairy and poultry units": { context: "Small dairy and poultry units may not have sensors, veterinarians, or regular monitoring systems. Problems become visible through illness, heat stress, or reduced output.", realProblem: "The challenge is to detect small changes early enough for an owner to take practical action before the loss becomes severe.", illustration: "A poultry owner notices birds are drinking more and moving less, but the signs do not yet look serious. What low-cost warning system could prompt action earlier?" },
  "Independent grading at the point of sale": { context: "Farmers may rely on a buyer's grading decision even though the grade directly affects the price they receive.", realProblem: "Farmers need a quick, understandable, and independent way to check quality at the collection or sale point.", illustration: "A buyer says a tomato lot is lower grade because of size and damage, but the farmer cannot verify the assessment. What could make the quality check visible and trustworthy?" },
  "Tracking losses in the first leg of the chain": { context: "Small lots travel from scattered farms through collection points before reaching a market or processor. Delays, heat, handling, and poor packaging can reduce value.", realProblem: "The chain often records final quantity or price but not where quality and value were lost, making it difficult to fix the highest-impact step.", illustration: "Produce from several villages reaches a processor partly spoiled, but nobody knows whether the loss happened during waiting, loading, transport, or storage. How would you locate the loss?" },
  "Consistent quality in micro food processing": { context: "Small food-processing units often depend on manual judgement instead of measured process steps, records, and repeatable quality checks.", realProblem: "A product can vary between batches in taste, safety, moisture, shelf life, or packaging, making it harder to build trust and grow.", illustration: "A women-led unit makes millet snacks, but one batch is crisp and another is soft because cooking time and moisture are judged by eye. What simple system could make every batch consistent?" },
  "Compliant labels for small food brands": { context: "Micro processors need labels that communicate product information and meet applicable requirements, but designing and updating labels can be difficult and costly.", realProblem: "The challenge is to make nutrition, allergens, ingredients, dates, batch details, and other required information easier to prepare correctly for small production runs.", illustration: "A small pickle brand changes its recipe, but the label still has old ingredients and date fields. How could compliant labels be created and checked simply?" },
  "Viable direct delivery to city buyers": { context: "Small producers may receive scattered orders from urban households. Delivery costs, distance, timing, and low order density can consume the margin.", realProblem: "Direct selling only works when ordering, aggregation, routing, payment, packaging, and repeat demand are coordinated well enough to beat the middleman route.", illustration: "Ten households in different parts of a city order small quantities from one farmer group. What would make direct delivery financially viable?" },
};

export default function HackathonPage() {
  return (
    <main className="bg-background">
      <section className="bg-deep py-20 text-deep-foreground sm:py-28">
        <div className="mx-auto max-w-6xl px-5 sm:px-8">
          <Breadcrumbs items={[{ name: "AgriTech Summit 2026", href: "/Agritech-summit-2026" }, { name: "Hackathon" }]} />
          <Link href="/Agritech-summit-2026" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-deep-muted hover:text-accent"><ArrowLeft className="h-4 w-4" /> Summit details</Link>
          <p className="mt-12 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.2em] text-accent"><Sprout className="h-4 w-4" /> AgriMinds Hackathon · 30 October 2026</p>
          <h1 className="font-display mt-6 max-w-4xl text-5xl font-semibold leading-[1.02] tracking-tight sm:text-7xl">Build solutions for real agricultural challenges.</h1>
          <p className="mt-7 max-w-3xl text-lg leading-relaxed text-deep-foreground/85 sm:text-xl">Choose one problem, understand the people affected, and develop a practical concept, prototype, or minimum viable product.</p>
          <a href="https://forms.gle/fyBmjV3jhQTLdKsP7" target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3 font-semibold text-accent-foreground transition hover:bg-accent-hover">Register for the Hackathon <ArrowRight className="h-4 w-4" /></a>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-24">
        <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Problem statements</p><h2 className="font-display mt-4 text-3xl font-semibold tracking-tight text-foreground-heading sm:text-5xl">Eleven opportunities to innovate, integrate, and create impact.</h2><p className="mt-5 text-lg leading-relaxed text-foreground-body">The challenges span the journey from seed and soil to farm operations, food processing, and market access.</p></div>
        <div className="mt-14 space-y-12">{problemTracks.map(([track, problems], trackIndex) => <section key={track} aria-labelledby={`hackathon-track-${trackIndex}`}><div className="border-b border-border pb-5"><p className="text-sm font-bold uppercase tracking-[0.18em] text-primary">Track {trackIndex + 1}</p><h2 id={`hackathon-track-${trackIndex}`} className="font-display mt-2 text-3xl font-semibold text-foreground-heading">{track}</h2></div><div className="mt-6 grid gap-5 md:grid-cols-2">{problems.map((problem, index) => { const brief = problemBriefs[problem]; return <details key={problem} className="group rounded-3xl border border-border bg-surface-card p-6 transition hover:border-accent/50 hover:shadow-lg sm:p-8"><summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden"><div className="flex items-start justify-between gap-4"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-soft text-primary"><Lightbulb className="h-5 w-5" /></span><span className="font-display text-3xl text-primary/30">{String(index + 1).padStart(2, "0")}</span></div><h3 className="font-display mt-7 text-xl font-semibold text-foreground-heading sm:text-2xl">{problem}</h3><span className="mt-5 inline-flex text-sm font-semibold text-primary group-open:text-accent">Read the full problem brief <span aria-hidden="true" className="ml-1">→</span></span></summary><div className="mt-7 space-y-5 border-t border-border pt-6"><div><h4 className="text-sm font-bold uppercase tracking-[0.14em] text-primary">Context</h4><p className="mt-2 leading-relaxed text-foreground-body">{brief.context}</p></div><div><h4 className="text-sm font-bold uppercase tracking-[0.14em] text-primary">What is the real problem?</h4><p className="mt-2 leading-relaxed text-foreground-body">{brief.realProblem}</p></div><div className="rounded-2xl bg-primary-soft px-4 py-4"><h4 className="text-sm font-bold uppercase tracking-[0.14em] text-primary">Illustration: a real-world scenario</h4><p className="mt-2 text-sm font-medium leading-relaxed text-foreground-heading">{brief.illustration}</p></div></div></details>; })}</div></section>)}</div>
      </section>

      <section className="bg-surface px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-6xl rounded-3xl bg-deep p-7 text-deep-foreground sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-accent">AgriMinds AgriTech Summit 2026</p><h2 className="font-display mt-4 max-w-3xl text-3xl font-semibold sm:text-4xl">Attend the summit, or register to build for the hackathon.</h2><div className="mt-8 flex flex-wrap gap-3"><a href="https://forms.gle/fyBmjV3jhQTLdKsP7" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-3 text-sm font-semibold text-accent-foreground transition hover:bg-accent-hover">Register for Hackathon</a><Link href="/Agritech-summit-2026" className="inline-flex items-center gap-2 rounded-full border border-deep-border px-5 py-3 text-sm font-semibold text-deep-foreground transition hover:border-accent">View Summit details</Link></div></div></section>
    </main>
  );
}
